Ext.define('LoadPrincipal.model.' + controller + '.List', 
{
    extend: 'Ext.data.Model',
    fields: [
        {name: '_id', mapping: '_id', type: 'string'},
		{name: 'address',  type: 'auto'},
		{name: 'created_at',  type: 'auto'},
		{name: 'arrival_time',  type: 'auto'},
		{name: 'code',  type: 'auto'},
		{name: 'created_at',  type: 'auto'},
        {name: 'duration', type: 'auto'},
		{name: 'finish_time', type: 'auto'},
		{name: 'forms', type: 'auto'},
		{name: 'id_company', type: 'auto'},
		{name: 'id_process', type: 'auto'},
		{name: 'id_user_update', type: 'auto'},
		{name: 'id_resourceInstance', type: 'auto'},
		{name: 'id_user_create', type: 'auto'},
		{name: 'loadAmount', type: 'auto'},
		{name: 'location', type: 'auto'},
		{name: 'name', type: 'auto'},
		{name: 'priority', type: 'auto'},
		{name: 'resourceInstance', type: 'auto'},
		{name: 'status', type: 'auto'},
		{name: 'statusConfigurations', type: 'auto'},
		{name: 'type', type: 'auto'},
		{name: 'updated_at', type: 'auto'},
		{name: 'checkin', type: 'auto'},
		{name: 'checkout', type: 'auto'},
    ],
    idProperty: '_id'
});
